[build]
 command = 'npm run build'
 publish = '/build'
 functions = './functions'


[[redirects]]
 from = "/api/*"
 to = "/.netlify/functions/:splat"
 status = 200

 //  redirecting to home page
[[redirects]]
  from = "/project"
  to = "/"
 status = 200
//  redirecting to projects api
[[redirects]]
  from = "/projects"
  to = "/api/projects"
 status = 200

 
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false